### ISSUE TITLE
Generic receiver shoudn't requires a SecretRef

### ISSUE THREAD

**Issue by vflaux** [fluxcd/notification-controller#135]
The notification-controller looks for a secret even when the receiver type is "generic".

According to the documentation: 
```
When the receiver type is set to generic, the controller will not perform token validation nor event filtering.
```
Is their actually a need for a token in this case ?

Shouldn't the `SecretRef` field be optional ?

**Comment by stefanprodan** [comment]
We use the token as seed for generating a unique webhook URL, so no, it can't be optional.
