### ISSUE TITLE
ExclusionList not working

### ISSUE THREAD

**Issue by jordivilaseca** [fluxcd/notification-controller#142]
I was trying to use this new feature to filter out some events that I don't want to be notified. After some time trying to remove really simple messges I checked the code and I think I saw a bug in the implementation.

I would say the problem is [here](https://github.com/fluxcd/notification-controller/blob/main/internal/server/event_handlers.go#L82). Continue instructions could be tricky, they continue to the next iteration in the inner bug. In that case there are two nested loops, so I would say this continue instruction will continue evaluating the next ExclusionList entry instead of going to the next event. As a result it never skips an event.

**Comment by squaremo** [comment]
That diagnosis is spot on -- thank you.
