### ISSUE TITLE
Annotate with the controller-runtime unstructured client 

### ISSUE THREAD

**Issue by stefanprodan** [fluxcd/notification-controller#150]
We should drop the dependencies to the GitOps Toolkit API packages and use the controller-runtime [unstructured client](https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/client/unstructured_client.go) to [annotate](https://github.com/fluxcd/notification-controller/blob/main/internal/server/receiver_handlers.go#L342) the GitOps Toolkit objects.

**Comment by SomtochiAma** [comment]
I am picking up this issue.
