### ISSUE TITLE
Add Sentry as a Provider

### ISSUE THREAD

**Issue by LWJ** [fluxcd/notification-controller#172]
We'd like to push reconciliation events to [sentry](https://sentry.io/). I've already done some investigation and started implementing using the [sentry-go](https://github.com/getsentry/sentry-go) library. Happy to make a PR and push my changes upstream if other members would find this integration useful.

**Comment by stefanprodan** [comment]
I see that sentry-go is a well maintained package, I'm ok with having Sentry support in Flux. We need to determine what extra fields the Provider needs, I'm not a Sentry user and I can't tell.

 @LWJ  could write here a proposal of how the Provider should look? Thanks

**Comment by LWJ** [comment]
Hi @stefanprodan, thanks for the response. I can give a brief overview:

Sentry uses something called a [DSN](https://docs.sentry.io/product/sentry-basics/dsn-explainer/) that gets passed to the SDK to inform it where to send events to. This is just a URL provided by Sentry with the following format:

`{PROTOCOL}://{PUBLIC_KEY}:{SECRET_KEY}@{HOST}{PATH}/{PROJECT_ID}`

Sentry users should already be familiar with using this DSN for integration, so I see no reason why we couldn't re-use the existing address field that other providers make use of. This should be the only field we need for the Sentry Provider.

For dispatching events, here is the payload model: https://develop.sentry.dev/sdk/event-payloads/

The go-sentry SDK will populate some of these fields for us (`event_id`, `platform`, `sdk`) - here is my proposal for mapping the others:

```go
&sentry.Event{
		Timestamp:  event.Timestamp.Time,
		Level:      sentry.Level(event.Severity),
		ServerName: event.ReportingController,
		Extra:      event.Metadata,
		Message:    event.Message,
	}
```

**Comment by stefanprodan** [comment]
@LWJ this looks great, I wasn't aware that DSN is just a URL, it fits perfectly with what we have in our API.

I'll assign this issue to you, looking forward to your PR, thanks again.
