### ISSUE TITLE
Notification controller does not start on clusters with active PSPs (runAsNonRoot)

### ISSUE THREAD

**Issue by pierluigilenoci** [fluxcd/notification-controller#178]
There isn't much more to add. 

```fmt
Error: container has runAsNonRoot and image has non-numeric user (controller), cannot verify user is non-root
```

**Comment by stefanprodan** [comment]
Create a PSP that allows the flux controller to run or patch them and hardcode some user id.

**Comment by pierluigilenoci** [comment]
@stefanprodan why you closed the ticket?

Isn't the right thing to do to add a security context here:
https://github.com/fluxcd/notification-controller/blob/main/config/manager/deployment.yaml#L22-L65

Something like:
```
	securityContext:
      runAsUser: 1001
```

**Comment by stefanprodan** [comment]
Please see: https://github.com/fluxcd/flux2/issues/829

**Comment by pierluigilenoci** [comment]
@stefanprodan according to sig-auth [1][2], a new implementation of PSP is on the way and will be backward compatible with old policies unless there are a few minor tweaks.
So I think calling PSP dead is a bit premature to me.

Ref:
[1] youtube.com/watch?v=YSzphARKjKs&t=2340s
[2] kubernetes/enhancements#5 (comment)

**Comment by pierluigilenoci** [comment]
FYI https://github.com/kubernetes/enhancements/pull/2582
