### ISSUE TITLE
Self Signed Cert on Github Provider

### ISSUE THREAD

**Issue by coultenholt** [fluxcd/notification-controller#183]
## Description
No option to specify TLS CA self signed cert in Provider Spec.

### Details
We run a GitHub enterprise server that has a self signed CA cert attached to it. When trying to set up git commit status, the notification controller gets the below error.

```
failed to send notification could not list commit statuses: ... : x509: certificate signed by unknown authority
```

Maybe a solution similar to the [ImageRepository](https://toolkit.fluxcd.io/components/image/imagerepositories/) CRD can be implemented in the provider as well. Specifically a value similar to `certSecretRef`?

**Comment by phillebaba** [comment]
I think the easiest way is to pass the CA in the Secret which contains the token, the issue here is that we would have to go back and implement support for all notifiers where applicable as it would be very confusing otherwise. Looking at the GitHub provider I see no issue adding an optional custom transport.

@stefanprodan any opinions?

**Comment by phillebaba** [comment]
After thinking about this for another second I realize that adding a `CertSecretRef` field to the provider would be better than reading it from the token secret.

**Comment by phillebaba** [comment]
@coultenholt I do not have access to a GitHub enterprise deployment, so could you have a look at the PR #184 and try it out to see if it solves your issue?

**Comment by coultenholt** [comment]
> @coultenholt I do not have access to a GitHub enterprise deployment, so could you have a look at the PR #184 and try it out to see if it solves your issue?

Will test just as soon as the [Docker Issue](https://status.docker.com/pages/history/533c6539221ae15e3f000031) is resolved.. :) Thanks for the quick turnaround!

**Comment by coultenholt** [comment]
> > @coultenholt I do not have access to a GitHub enterprise deployment, so could you have a look at the PR #184 and try it out to see if it solves your issue?
> 
> Will test just as soon as the [Docker Issue](https://status.docker.com/pages/history/533c6539221ae15e3f000031) is resolved.. :) Thanks for the quick turnaround!

@phillebaba Your PR worked for me! Would love to get this merged in and released! Thank you!

**Comment by phillebaba** [comment]
Great to hear that! I just need to write some tests and fix some smaller issues and we should be good to go.
