### ISSUE TITLE
Adding cluster name (or something else) to Github commit status context

### ISSUE THREAD

**Issue by gmaiztegi** [fluxcd/notification-controller#194]
We run a few clusters with Flux and are moving towards Flux 2 now, and so far the experience is being awesome.

We have seen an issue in this notification controller, and it's that when having multiple clusters posting the commit status for the same resource names (such as `kustomization/flux-system`), the statuses get overwritten, as they use the `<resource type>/<name>` as context.

Therefore, it would be awesome if we could add some kind of prefix or suffix to this context in order to distinguish the status posted by the different clusters.

And once again, Flux 2 is great. Thanks for your hard work.

**Comment by phillebaba** [comment]
I agree that we should have a second look at this. When we first implemented the commit status feature a lot was unknown. Currently I am solving this by adding the environment or cluster name to the Kustomization resource. This will cause the statuses to be unique between different clusters.

One solution may be to expose some sort of format configuration for the provider. A risk is that users would hit the character limit for a status message. Most of the providers have one but they are not documented so they are found by trial and error. Do you have any suggestion for how this configuration should be implemented in the provider or alert resource @gmaiztegi?

**Comment by gmaiztegi** [comment]
I'm not sure on wether it should be on the provide or the alert. It seems that this is a Github specific issue regarding the commit status, although the question might be wether it might be useful to have different alerts with different identifiers, all of them pointing to the Github provider. It's not our use case, nor I can think of any right now, but this seems more flexible.

**Comment by gdoctor** [comment]
On a related note, adding some cluster metadata to a notification would be extremely valuable. I am also running flux on 20+ clusters now, and we are unable to use the notification controller effectively since we cannot tell where the notification originated without having a separate chat room per notification-controller instance (we are going to have 50 or more clusters so not very reasonable).

**Comment by stefanprodan** [comment]
@gdoctor you can add the cluster name to the alert message with `spec.summary`, docs here: https://fluxcd.io/docs/components/notification/alert/

**Comment by bforchhammer** [comment]
Hi, I've also run into the issue described here, and adding the "summary" to an "alert" unfortunately does not seem to do anything in the case of github status messages; github status seem to only contain the `kind`/`name` of the referenced object and the `event reason` as defined in `formatNameAndDescription` here: https://github.com/fluxcd/notification-controller/blob/c4377ceb51f0ed969aa3fac1c151189bfa18d7fc/internal/notifier/util.go#L47

**Comment by jrauschenbusch** [comment]
@stefanprodan Is there any progress regarding the dedicated `CommitStatus` CRD? This would extend the room of enhancements by far (e.g. https://github.com/fluxcd/notification-controller/issues/225)
