### ISSUE TITLE
Slack provider for a private channel doesn't work

### ISSUE THREAD

**Issue by messiahUA** [fluxcd/notification-controller#200]
I have an incoming webhook configured for a specific private channel and as far as I know slack has made a change at some point that it's forbidden to specify the channel name in this case, so it's impossible to use such webhook because "channel" is mandatory https://github.com/fluxcd/notification-controller/blob/337b5ab624512818ccbba6e35fecc750a004b770/internal/notifier/slack.go#L69

When I'm testing the webhook url using curl it works perfectly fine without specifying the channel, but if I specify it I always get "channel_not_found". And notification controller is completely silent about this.

**Comment by phillebaba** [comment]
Is there a way that we can differentiate between the webhooks that require a channel and webhooks that dont?

**Comment by messiahUA** [comment]
I don’t think there is a way to do that based only on the webhook url. And as far as I know webhooks should have a default channel configured, so it should be left for the flux user to specify the channel or not and thus it should be optional.

If I’m wrong and there is an option that channel may be indeed mandatory (on the slack side) then controller should just log an error returned from the slack.

**Comment by SomtochiAma** [comment]
I will take a look at this issue

**Comment by SomtochiAma** [comment]
Hey @messiahUA,
Specifying the name of the channel still works for me, events get posted to the slack channel.
I agree with you though we should consider the name of channel not being required. But specifying it in this case still works for me.
I have been unable to reproduce this. Or is there something I am missing?

**Comment by SomtochiAma** [comment]
Making a curl request(with data `'{"text":"Hello, World!", "channel":"test-private"}'`) also works.
Did you structure your curl request differently?

**Comment by messiahUA** [comment]
I've tried once again with the same webhook and it works. Even tried to different private channels. I'm confused, not sure what's going on here and what changed... Maybe I made a mistake, but not sure how it is possible because I did same simple curl request. Anyways, can't explain it right now.

**Comment by stefanprodan** [comment]
This could’ve been a transient issue on the Slack side.

**Comment by SomtochiAma** [comment]
I noticed that specifying any random string as the channel name still works(not adding the field still works too).
It seems the channel field is not actually required for slack.
@stefanprodan wdyt? Should we make the `channel` field optional for slack?

**Comment by stefanprodan** [comment]
There was no default channel required in Slack UI, if this has changed then yes we could remove our validation.
