### ISSUE TITLE
Azure DevOps: CreateCommitStatus not using context with timeout

### ISSUE THREAD

**Issue by simongottschlag** [fluxcd/notification-controller#205]
Hi!

When going through the code I noticed that when sending status to Azure DevOps, a context with timeout isn't being used even though it's created.

This is where the status is sent:
https://github.com/fluxcd/notification-controller/blob/f1cc79039877f9a18b95ee4ef8750ffacc607102/internal/notifier/azure_devops.go#L133

This is where the context with timeout is created a little earlier:
https://github.com/fluxcd/notification-controller/blob/f1cc79039877f9a18b95ee4ef8750ffacc607102/internal/notifier/azure_devops.go#L100-L101

**Comment by makkes** [comment]
closed in #385
