### ISSUE TITLE
Support Bitbucket Cloud - allow operation without a secret token

### ISSUE THREAD

**Issue by kingdonb** [fluxcd/notification-controller#218]
I was going to document the Bitbucket Cloud support for webhook receivers, but it turns out that [Bitbucket Cloud does not support passing a secret in the webhook](https://jira.atlassian.com/browse/BCLOUD-14683), which is an extremely questionable decision IMHO and leaves webhook receivers open to risk of DoS, but this can apparently be mitigated by allow-listing the Bitbucket Cloud IP range.

I saw in the Receiver spec that `secretRef` has the `omitEmpty` tag, and got excited... but:

```
	// Secret reference containing the token used
	// to validate the payload authenticity
	// +required
	SecretRef meta.LocalObjectReference `json:"secretRef,omitempty"`
```

it is also tagged as required, (though I was able to create a Receiver without any secretRef and it was not rejected by validation, the result was not positive...)

```
flux-system   flux-system   False   unable to read token from secret 'flux-system/' error: Secret "" not found   1s
```

So, it is really required, and it is not presently possible to create any webhook receiver that will work with Bitbucket Cloud.

Is any remediation possible? I have raised a few objections to my own proposal above, and I'm not sure if we can provide a "no-secret-token" mode – since that issue has sat on Bitbucket's Jira instance since 2017, I'm inclined to think it's likely to have been a strategic decision to promote their Enterprise Bitbucket Stash or Server products, and they won't be fixing it.

**Comment by stefanprodan** [comment]
We can’t remove the secret as it’s being used to generate a unique ingress route. No matter the provided capabilities, users have to create a secret with a random token.

**Comment by kingdonb** [comment]
So the best we can do I guess is add some "insecure" flag or maybe "insecure" provider, that ignores an incorrect content or absence of the secret token in any POST requests so long as they are actually received through the correct route.

The path itself could be considered a secret, since it is randomly generated I'm not sure this is actually much less secure.

(I'll go try implementing this!)
