### ISSUE TITLE
Add support for Telegram notifications

### ISSUE THREAD

**Issue by TrAnn3l** [fluxcd/notification-controller#222]
Hey, it would be great if you could add support for Telegram notifications.

You just have make a POST or GET request to specific URL with a few parameters.
The follwing docs show the basics:
https://core.telegram.org/bots/api#making-requests
And for the message one need to use the following method:
https://core.telegram.org/bots/api#sendmessage
The user would only need to supply the URL and the chat_id.
As message formatting, markdown and html is possible.

If you need any further information, feel free to ask.
Thank you in advance :)

**Comment by dholbach** [comment]
Would it makes sense to use https://github.com/containrrr/shoutrrr? It's used in `weaveworks/kured` now.

**Comment by stefanprodan** [comment]
@dholbach that library looks great 👍

**Comment by dholbach** [comment]
@atighineanu is in the #kured Slack channel and has helped out quite a bit.

**Comment by TrAnn3l** [comment]
Looks also great to me!

**Comment by SomtochiAma** [comment]
Picking this up
