### ISSUE TITLE
Some resources always send a notification

### ISSUE THREAD

**Issue by mbrancato** [fluxcd/notification-controller#234]
Is there a way that we can prevent notifications for "changes" to resources that are not being changed? I don't know the best way to actually determine if changes were made, maybe this is an upstream issue.

It might be that this is caused by the `kustomize.toolkit.fluxcd.io/checksum` label. Is there any way to ignore this since we get flooded with objects being changed when they are not.

**Comment by heschlie** [comment]
The ImagePolicy resource also spams notifications. I feel like most folks would expect notifications to only be "Hey this thing changed" as right now those get lost in all of the "Hey here is the same message I posted 5 minutes ago".

**Comment by uderik** [comment]
I have not found a normal solution to send messages only for new image releases  via alert, ImagePolicy spam message on every scan

**Comment by stefanprodan** [comment]
Please open an issue here about policy spam: https://github.com/fluxcd/image-reflector-controller
