### ISSUE TITLE
issue regarding receiver unique URL

### ISSUE THREAD

**Issue by leoxhj** [fluxcd/notification-controller#292]
### Describe the bug

Hello team,

Today we noticed the receiver unique URL seems has been changed for some reason which caused the webhook delivery failed.
Maybe I know is that how it was designed or is it a bug?

for example:
We get the receiver unique id below, but after 2 days, it was changed another uid.

[root@localhost ~]# kubectl get receivers -n supply-replenishment|awk '{print $7}'|awk -F '/' '{print $3}'

b28e3bf918efd723e027031a3ad99ab67f83e82b35e7b7a1904de8bea476b3c6

### Steps to reproduce

dunno

### Expected behavior

we expected this unique url is never changed.

### OS / Distro

centos 7.x

### Flux version

v 0.15

### Flux check

[root@localhost ~]# flux check
► checking prerequisites
✗ flux 0.17.0 <0.23.0 (new version is available, please upgrade)
✔ kubectl 1.22.1 >=1.18.0-0
✔ Kubernetes 1.20.7 >=1.16.0-0
► checking controllers
✔ helm-controller: deployment ready
► acrcsz.azurecr.cn/fluxcd/helm-controller:v0.11.1
✔ image-automation-controller: deployment ready
► acrcsz.azurecr.cn/fluxcd/image-automation-controller:v0.14.0
✔ image-reflector-controller: deployment ready
► acrcsz.azurecr.cn/fluxcd/image-reflector-controller:v0.11.0
✔ kustomize-controller: deployment ready
► acrcsz.azurecr.cn/fluxcd/kustomize-controller:v0.13.1
✔ notification-controller: deployment ready
► acrcsz.azurecr.cn/fluxcd/notification-controller:v0.15.0
✔ source-controller: deployment ready
► acrcsz.azurecr.cn/fluxcd/source-controller:v0.15.3
✔ all checks passed

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by leoxhj** [comment]
`2021-11-24 14:14:00`

[root@localhost ~]# kubectl get receivers -n supply-replenishment
NAME                            READY   STATUS                                                                                                  AGE
supply-replenishment-receiver   True    Receiver initialised with URL: /hook/b28e3bf918efd723e027031a3ad99ab67f83e82b35e7b7a1904de8bea476b3c6   29d

`2021-11-24 half an hour later`

[root@localhost ~]# kubectl get receiver -n supply-replenishment
NAME                            READY   STATUS                                                                                                  AGE
supply-replenishment-receiver   True    Receiver initialised with URL: /hook/271fc4cf01831b771b4282851a8bca859ba94709e21803cb85fb21497e2f393d   30d

**Comment by leoxhj** [comment]
attached notification-controller log:


[notification-controller-69df9985c6-xjt6h.log](https://github.com/fluxcd/notification-controller/files/7593892/notification-controller-69df9985c6-xjt6h.log)

**Comment by leoxhj** [comment]
I think we found the log, but nothing has been changed at that moment.

{"level":"info","ts":"2021-11-24T06:18:36.400Z","logger":"controller.receiver","msg":"Receiver initialised","reconciler group":"notification.toolkit.fluxcd.io","reconciler kind":"Receiver","name":"supply-replenishment-receiver","namespace":"supply-replenishment"}
{"level":"info","ts":"2021-11-24T06:18:36.408Z","logger":"controller.receiver","msg":"Receiver initialised","reconciler group":"notification.toolkit.fluxcd.io","reconciler kind":"Receiver","name":"shiphub-receiver","namespace":"shiphub"}
{

**Comment by stefanprodan** [comment]
The only way this could happen is when the secret value changed: https://github.com/fluxcd/notification-controller/blob/main/controllers/receiver_controller.go#L155 

@SomtochiAma can you please refactor the unit tests and add a test to prove that the URL doesn't change unless the secret changes?

**Comment by leoxhj** [comment]
btw, please help to validate this on v0.15.0

https://github.com/fluxcd/notification-controller/blob/v0.15.0/controllers/receiver_controller.go

**Comment by leoxhj** [comment]
@hiddeco @stefanprodan @SomtochiAma Thanks for your detail clarification, you're right.  It seems our helmchart deployment update the secret for some reason, we still need to figure out ourselves. Again, thanks a lot. please close my issue.
