### ISSUE TITLE
Allow using Basic Auth in Grafana provider

### ISSUE THREAD

**Issue by antoineozenne** [fluxcd/notification-controller#332]
### Describe the bug

This is a feature request.

To send notifications to [Grafana annotations API](https://grafana.com/docs/grafana/latest/http_api/annotations/), the Grafana Provider only allows using API key to authenticate to Grafana (<https://fluxcd.io/docs/components/notification/provider/#grafana>). To create an API key in Grafana, we must manually authenticate with an account via UI or API (so after Grafana is deployed). So it is impossible to deploy and configure Flux monitoring without any manual step (for a new environment, for example). I think this is not really GitOps compliant. Is it possible to use Basic Auth in the Grafana Provider?

### Steps to reproduce

N/A

### Expected behavior

N/A

### OS / Distro

N/A

### Flux version

v0.26.3

### Flux check

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fsequeira1** [comment]
I will look into it
