### ISSUE TITLE
notification-controller error with provider sops & azure devops

### ISSUE THREAD

**Issue by soufianez75** [fluxcd/notification-controller#422]
Hello,

I have an issue when i apply a provider with type azuredevops

{"level":"info","ts":"2022-09-22T14:37:39.284Z","logger":"event-server","msg":"Dispatching event: Provider/ns/notification dry-run failed, error: failed to create typed patch object (ns/notification; notification.toolkit.fluxcd.io/v1beta1, Kind=Provider): .spec.decryption: field not declared in schema\n","reconciler kind":"Kustomization","name":"app","namespace":"ns"}

issue with the CRD ?

**Comment by stefanprodan** [comment]
There is no `.spec.decryption` in the notification-controller APIs, what are you trying to do?

**Comment by soufianez75** [comment]
I use an secret encrypt with sops

**Comment by stefanprodan** [comment]
Such a thing is not possible, only Flux Kustomization objects support decryption.

**Comment by soufianez75** [comment]
It's OK thanks a lot
