### ISSUE TITLE
GA: Promote `Receiver` to `notification.toolkit.fluxcd.io/v1`

### ISSUE THREAD

**Issue by stefanprodan** [fluxcd/notification-controller#436]
Items to be reviewed plus any outstanding work required to bump the API to `v1`:
- [x] Documentation
  - [x] https://fluxcd.io/flux/guides/webhook-receivers/
  - [x] https://fluxcd.io/flux/guides/image-update/#trigger-image-updates-with-webhooks
  - [x] https://fluxcd.io/flux/guides/helmreleases/#configure-webhook-receivers
  - [x] https://fluxcd.io/flux/migration/helm-operator-migration/#added-support-for-notifications-and-webhooks
  - [x] https://fluxcd.io/flux/components/notification/options/#flags
  - [x] https://fluxcd.io/flux/components/notification/receiver/
  - [x] https://fluxcd.io/flux/components/notification/api/#notification.toolkit.fluxcd.io/v1beta2.Receiver
  - [x] https://fluxcd.io/flux/gitops-toolkit/packages/#go-packages
  - [x] https://fluxcd.io/flux/flux-e2e/#trigger-reconciling-on-git-push-with-webhook-receivers
  - [x] https://fluxcd.io/flux/cheatsheets/bootstrap/#enable-notifications-for-third-party-controllers
- [x] API Validation
  - [x] all Receiver API fields are accompanied with proper validation if possible
  - [x] the validation is reflected in the documentation, particuarly https://fluxcd.io/flux/components/notification/receiver/.
- [x] Test Coverage
  - [x] ReceiverReconciler: 94.9% direct coverage
- [x] #498
- [x] #499
- [x] #503
- [x] tag v1 release

Depends on: #435

**Comment by makkes** [comment]
all done
