### ISSUE TITLE
Alert EventSeverity has no default value

### ISSUE THREAD

**Issue by phillebaba** [fluxcd/notification-controller#44]
The documentation states that if EventSeverity is not set it will default to `info`. I cannot find any code that sets the default value.

```go
// Filter events based on severity, defaults to ('info').
// +kubebuilder:validation:Enum=info;error
// +optional
EventSeverity string `json:"eventSeverity,omitempty"`
```

Additionally the check for EventSeverity has an undocumented behavior. As I understand it an Alert will be sent either if the EventSeverity of the event matches the alert. Or if the Alert severity is of type `info`. If this is the intended behavior it should be documented that setting the severity to `info` will also include alerts with severity `error`.
https://github.com/fluxcd/notification-controller/blob/20f07c809644fb45aae76ac185ffa5b9d4d73386/internal/server/event_handlers.go#L80-L81

**Comment by stefanprodan** [comment]
We need to set the default in code and document that the `info` filter includes errors.

**Comment by phillebaba** [comment]
We should probably start using [annotations](https://book.kubebuilder.io/reference/markers/crd-validation.html) to set default values.
```
// +kubebuilder:default := <any>
```

Have a quick look through the CRDs while I am at it, to see if we are missing any other default values.

**Comment by stefanprodan** [comment]
Defaults are not supported by all Kubernetes versions, we should handle this in code.

**Comment by phillebaba** [comment]
How long will it be until we start using CRD v1 features? 1.16 is the earliest version that supports them. Currently EKS and AKS are at 1.17 as their latest version. Do we have a minimum version that we are targeting?

**Comment by stefanprodan** [comment]
@phillebaba we are using CRD v1 and the minimum Kubernetes version is 1.16. If the default work on 1.16 we could use it for sure.
