### ISSUE TITLE
Webhooks sharing port with pprof endpoints

### ISSUE THREAD

**Issue by ArchiFleKs** [fluxcd/notification-controller#449]
### Describe the bug

The [doc](https://fluxcd.io/flux/gitops-toolkit/debugging/#pprof) says that pprof is supposed to listen on port 8080 (http-prom). But it also listen on port 9292, which means when exposing port 9292 via ingress for Webhook pprof is also exposed on the outside.

### Steps to reproduce

1. kubectl -n flux-system port-forward notification-controller... 9292
2. curl localhost:9292/debug/pprof

### Expected behavior

pprof should only listen on private 8080 http-prom port

### OS / Distro

Bottlerocket 1.11

### Flux version

v0.37.0

### Flux check

► checking prerequisites
✔ Kubernetes 1.22.15-eks-fb459a0 >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.27.0
✔ image-automation-controller: deployment ready
► ghcr.io/fluxcd/image-automation-controller:v0.27.0
✔ image-reflector-controller: deployment ready
► ghcr.io/fluxcd/image-reflector-controller:v0.23.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.31.0
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.29.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.32.1
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta1
✔ buckets.source.toolkit.fluxcd.io/v1beta1
✔ gitrepositories.source.toolkit.fluxcd.io/v1beta1
✔ helmcharts.source.toolkit.fluxcd.io/v1beta1
✔ helmreleases.helm.toolkit.fluxcd.io/v2beta1
✔ helmrepositories.source.toolkit.fluxcd.io/v1beta1
✔ imagepolicies.image.toolkit.fluxcd.io/v1beta1
✔ imagerepositories.image.toolkit.fluxcd.io/v1beta1
✔ imageupdateautomations.image.toolkit.fluxcd.io/v1beta1
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1beta1
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta1
✔ receivers.notification.toolkit.fluxcd.io/v1beta1
✔ all checks passed

### Git provider

Github

### Container Registry provider

ECR

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pjbgf** [comment]
@ArchiFleKs thank you for reporting this issue. @darkowlzz came up with a fix for this, can you please test and confirm it behaves as expected? Here's the rc image: `ghcr.io/fluxcd/notification-controller:rc-ac17d75b`.

**Comment by ArchiFleKs** [comment]
> @ArchiFleKs thank you for reporting this issue. @darkowlzz came up with a fix for this, can you please test and confirm it behaves as expected? Here's the rc image: `ghcr.io/fluxcd/notification-controller:rc-ac17d75b`.

Thanks, it solves the issue !

**Comment by pjbgf** [comment]
We have just included the fix on the official patch release: `ghcr.io/fluxcd/notification-controller:v0.29.1`.
