### ISSUE TITLE
Filter events sent by different types of notifiers

### ISSUE THREAD

**Issue by phillebaba** [fluxcd/notification-controller#45]
The kustomization controller limits the amount of events sent to the notification controller, to limit the amount of message sent by the chat notifiers (Slack, MS Teams, etc.). If this was not done the messages would be very verbose, as events would be sent every reconcile loop, even when nothing has changes.

On the other hand the git notifiers need to receive succeeded events if a deployment goes from unhealthy to healthy without the revision changing.

These two requirements are at odds with each other. To deal with this the chat notifiers need to filter out any succeeded events where the revision has not changed from the last sent event.

**Comment by stefanprodan** [comment]
We could solve this with:
- make commit status ignore events with reason `Progressing` 
- issue events from kustomize-controller after each successful reconciliation with metadata `commit_status: "update"`
- make alerts ignore successful events with metadata `commit_status: "update"` if type is Slack/Teams/etc
