### ISSUE TITLE
Namespace fallback for annotation logs

### ISSUE THREAD

**Issue by tun0** [fluxcd/notification-controller#492]
Ref: https://github.com/fluxcd/notification-controller/blob/7448a667a0c9b49c0f6c9940034e08e830a37ab6/internal/server/receiver_handlers.go#L96-L105

Currently my logs are showing like `resource '<Kind>/<Name>.' annotated`. Note the trailing dot after `<Name>`. It would be nice to either:
* Make that dot optional when `resource.Namespace` isn't defined.
* Fallback to `receiver.Namespace` if `resource.Namespace` isn't defined.

**Comment by knutgoetz** [comment]
Isn't this already fixed and can be closed?
Right now the `defaultNamespace` is set as the namespace and as far as i can tell the method is always called with `defaultName` set to the namespace of the relevant `Receiver` resource.

https://github.com/fluxcd/notification-controller/blob/820fe53ce7b549b2ffb11e9296de377a0a042dea/internal/server/receiver_handlers.go#L367-L371

Updated original snippet:
https://github.com/fluxcd/notification-controller/blob/820fe53ce7b549b2ffb11e9296de377a0a042dea/internal/server/receiver_handlers.go#L411-L417

**Comment by makkes** [comment]
Good catch. Yes, this has been fixed as a side effect of #482 and is included in all version starting from 1.0.0 (i.e. Flux 2.0.0+).
