### ISSUE TITLE
Flux not creating alert/provider defined in file, only works via CLI

### ISSUE THREAD

**Issue by acdoussan** [fluxcd/notification-controller#494]
I have tried a ton of combinations of things but have not been able to successfully create an alert using yaml files. The following is what I have done:

```
$ flux create alert-provider discord-provider \
  --type discord \
  --secret-ref discord-url

$ flux create alert \                                      
  --event-severity info \
  --event-source "Kustomization/*,GitRepository/*" \
  --provider-ref discord-provider \
  flux-alerts

$ kubectl -n flux-system get alerts                                                   
NAME          AGE   READY   STATUS
flux-alerts   30s   True    Initialized

<alert was created here and I got a successful alert in discord>

$ flux export alert-provider discord-provider > flux-system/discord-provider.yaml

$ flux export alert flux-alerts > flux-system/discord-alert.yaml

$ flux delete alert flux-alerts

$ flux delete alert-provider discord-provider

$ kubectl -n flux-system get alerts
No resources found in flux-system namespace.

<I then committed these files and pushed them, flux picked up the latest commit and then did nothing>

$ kubectl -n flux-system get alerts
No resources found in flux-system namespace.
```

flux-system/discord-alert.yaml
```
---
apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Alert
metadata:
  name: flux-alerts
  namespace: flux-system
spec:
  eventSeverity: info
  eventSources:
  - kind: Kustomization
    name: '*'
  - kind: GitRepository
    name: '*'
  providerRef:
    name: discord-provider
```

flux-system/discord-provider.yaml
```
---
apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Provider
metadata:
  name: discord-provider
  namespace: flux-system
spec:
  secretRef:
    name: discord-url
  type: discord
```

```
$ flux --version
flux version 0.40.2

$ kubectl version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.26.1
Kustomize Version: v4.5.7
Server Version: v1.24.9+k3s1
```

**Comment by makkes** [comment]
Have you created any source (e.g. GitRepository) and Kustomization on the cluster?

**Comment by acdoussan** [comment]
You mean like this?

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
- discord-alert.yaml
- discord-provider.yaml
```

committed and pushed this, same thing, still no alert created

**Comment by acdoussan** [comment]
There is also nothing really mentioned about needing to do this in the docs from what I can tell? The example wants you to run a kubectl command, and the video / outside docs I've been following also don't mention anything about this.

https://fluxcd.io/flux/components/notification/alert/
https://docs.technotim.live/posts/flux-devops-gitops/
https://github.com/techno-tim/launchpad/tree/master/demos/flux-demo/clusters/home

**Comment by acdoussan** [comment]
Is there anywhere I can look for errors or logs where this resource is supposed to be created?

**Comment by acdoussan** [comment]
Ok sorry, I take it back, adding the files to kustomization.yaml did work. I had a bad helm configuration for longhorn, and it looks like that was causing errors in `kustomization/flux-system` for some reason (namespace was missing).

Should this be documented somewhere?

**Comment by makkes** [comment]
> There is also nothing really mentioned about needing to do this in the docs from what I can tell? The example wants you to run a kubectl command, and the video / outside docs I've been following also don't mention anything about this.
> 
> https://fluxcd.io/flux/components/notification/alert/

The documentation is supposed to be generic. We cannot take all permutations of different configuration options into account there.

> https://docs.technotim.live/posts/flux-devops-gitops/ https://github.com/techno-tim/launchpad/tree/master/demos/flux-demo/clusters/home

Both of these pages are not maintained by the Flux project.

**Comment by makkes** [comment]
> Is there anywhere I can look for errors or logs where this resource is supposed to be created?

https://fluxcd.io/flux/cmd/flux_logs/
