### ISSUE TITLE
Enable Terraform resource monitoring

### ISSUE THREAD

**Issue by sergiogarciarodriguez** [fluxcd/notification-controller#502]
Currently there is no support for tf-contoller resources notifications, I didn't find any way to make notification-contoller work along tf-controller with current configuration but adding `Terraform` into notification-contoller CRDs make it work.

{"level":"info","ts":"2023-03-28T07:46:29.549Z","logger":"event-server","msg":"Discarding event, no alerts found for the involved object","reconciler kind":"Terraform","name":"usw2-blue-cluster","namespace":"test-alert-aws-global-dev"}

Adding `Terraform` to eventSources into alerts, providers and receivers CRDs (https://github.com/fluxcd/notification-controller/blob/0863edc6e6d5a639f240f9945800ceeab7bd3f78/config/crd/bases/notification.toolkit.fluxcd.io_alerts.yaml#L273) makes possible to create alerts with kind `Terraform` like the following able to filter and notify properly:

```apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Alert
metadata:
  name: terraform-alert
  namespace: flux-system
spec:
  providerRef:
    name: slack
  eventSeverity: error
  eventSources:
  - kind: Terraform
    name: "*"
    namespace: "test-alert-aws-global-dev"
```

Applying this alert event is filtered properly resulting in notification:

{"level":"info","ts":"2023-03-28T08:18:48.539Z","logger":"event-server","msg":"Dispatching event: Drift detected.\n\nChanges to Outputs:\n  # Warning: this attribute value will be marked as sensitive and will not\n  # display in UI output after applying this change.\n  ~ kubeconfig = (sensitive value)\n\n\n","reconciler kind":"Terraform","name":"usw2-blue-cluster","namespace":"test-alert-aws-global-dev"}

<img width="823" alt="image" src="https://user-images.githubusercontent.com/44770033/228176073-d94b074c-bbdd-420c-94ce-5ac061852d6e.png">

Please, let me know if I'm doing something the wrong way. Thank you!

**Comment by stefanprodan** [comment]
Please see the docs here: https://fluxcd.io/flux/cheatsheets/bootstrap/#enable-notifications-for-third-party-controllers

**Comment by sergiogarciarodriguez** [comment]
Thank you very much, I didn't notice that part of documentation. Should I include provider CRD patch? @stefanprodan

**Comment by sebastiangaiser** [comment]
Link to updated docs: https://weaveworks.github.io/tf-controller/how_to/flux_receiver_and_alert/
