### ISSUE TITLE
Support for BitBucket server as Git commit status update provider

### ISSUE THREAD

**Issue by eloo-abi** [fluxcd/notification-controller#507]
Hi,

i have just seen that "Bitbucket" is supported as Git commit status update provider. 
But it looks like it is currently hard coded to the cloud instance and so its not supporting BitBucket server instance.

https://github.com/fluxcd/notification-controller/blob/main/internal/notifier/bitbucket.go#L122

Are there any plans to support bitbucket server as well?

Thanks

**Comment by jbehrends** [comment]
My team just ran into this issue as well.  No where in the documentation does it state this is a "Bitbucket Cloud" only feature.  Seems like the URL could just be exposed as part of the CRD object for the notification provider?  That way end-users could just configure the server URL themselves to use either cloud or on-prem versions of Bitbucket.

**Comment by gdasson** [comment]
@eloo-abi This issue can now be closed, the functionality will be available in next release.
