### ISSUE TITLE
Feature request: Add inclusion list to `Alert` CRD

### ISSUE THREAD

**Issue by aristapimenta** [fluxcd/notification-controller#512]
Sometimes we are only interested in a single event, e.g. `Helm upgrade succeeded`, in which case it would be much easier to specify an inclusion list rather than an exclusion list.

**Comment by stefanprodan** [comment]
@aristapimenta are you willing to contribute this feature?

**Comment by aristapimenta** [comment]
> @aristapimenta are you willing to contribute this feature?

I'd be honored!

**Comment by matheuscscp** [comment]
Would that be API `v1` or `v1beta2`? :thinking:
