### ISSUE TITLE
Docs - v1beta2 - Providers - Key type

### ISSUE THREAD

**Issue by michaelsatish** [fluxcd/notification-controller#581]
There is a type issue in the example provided for Generic Webhook with HMAC. 

https://github.com/fluxcd/notification-controller/blob/main/docs/spec/v1beta2/providers.md#generic-webhook-with-hmac

The function verifySignature takes a key of type byte array.
```go
func verifySignature(signature string, payload, key []byte) error
```

A string value is provided to the function when it gets called in the `handleRequest` function
```go
// Verify signature using the same token as the Secret referenced in
// Provider
key := "<token>"
if err := verifySignature(r.Header.Get("X-Signature"), body, key); err != nil {
    http.Error(w, fmt.Sprintf("failed to verify HMAC signature: %s", err.Error()), http.StatusBadRequest)
    return
}
```

**Comment by somtochiama** [comment]
@michaelsatish thanks for catching this.

The key can be converted to a byte array. as it is passed to the function.
Would you like to open a PR for it?

**Comment by michaelsatish** [comment]
@somtochiama More than happy to open a PR. Opened PR #585
