### ISSUE TITLE
Receiver match on labels

### ISSUE THREAD

**Issue by sebastiangaiser** [fluxcd/notification-controller#681]
Hey, 

I found this issue about wildcard matching of all resources (https://github.com/fluxcd/notification-controller/issues/461).
I think it could be a nice way to handle this also via labels - more or less the same way as prometheus-operator does it.

Example from prometheus-operator - prometheus cr:
```
podMonitorSelector:
    matchLabels:
      team: example
```

**Comment by stefanprodan** [comment]
Alerts have label selectors https://fluxcd.io/flux/components/notification/alerts/#select-objects-by-label for Receiver it doesn't make sense to me as the webhook is a one-to-one with a single source.

**Comment by sebastiangaiser** [comment]
Haven't seen it on the Alerts, sorry.

Regarding the Receiver, I think our setup is maybe a bit, let's call it special: 
We have a setup with some repository local charts. For this we create tags for each Helm chart when pushed to main. To now have a versioning on them we create a GitRepository pointing to the correct revision of the Helm chart. Maybe that's not the best way but maybe you know understand the use case.

**Comment by stefanprodan** [comment]
Receiver v1 does support label selectors now: https://fluxcd.io/flux/components/notification/receivers/#reconcile-objects-by-label
