### ISSUE TITLE
Add alternative key name for the commit status secret

### ISSUE THREAD

**Issue by stefanprodan** [fluxcd/notification-controller#745]
Currently we expect for the GitHub/GitLab/etc PAT to be set under the `token` key in the Kubernetes Secret referenced in the Provider https://fluxcd.io/flux/components/notification/providers/#github

If `token` is not found in the secret, but there is a `password` field, we should be using it instead. The reason being that, when using a PAT for `flux bootstrap --token-auth`, the PAT is set in the `password` field. So instead of creating a new secret with the same token for the Provider, users should be able to reuse the secret created by bootstrap.

**Comment by sarataha** [comment]
Hello Stefan, I would like to work on this issue 🙂
