### ISSUE TITLE
Error notifications contain too much not error data

### ISSUE THREAD

**Issue by sylr** [fluxcd/notification-controller#81]
Hi 👋 ,

I believe that error messages are too verbose and should focus more on the actual error, e.g. (taken from a slack notification):

```
apply failed: secret/flux-known-hosts-79bt28cg56 unchanged
secret/gitlab-infra-company-com unchanged
secret/slack-live-team-ops unchanged
service/notification-controller unchanged
deployment.apps/kustomize-controller unchanged
kustomization.kustomize.toolkit.fluxcd.io/aks07-euw-dev-link-default unchanged
kustomization.kustomize.toolkit.fluxcd.io/aks07-euw-dev-link-flux unchanged
kustomization.kustomize.toolkit.fluxcd.io/aks07-euw-dev-link-ingress unchanged
kustomization.kustomize.toolkit.fluxcd.io/aks07-euw-dev-link-kube-system unchanged
kustomization.kustomize.toolkit.fluxcd.io/aks07-euw-dev-link-logging unchanged
kustomization.kustomize.toolkit.fluxcd.io/aks07-euw-dev-link-maintenance unchanged
kustomization.kustomize.toolkit.fluxcd.io/aks07-euw-dev-link-monitoring unchanged
alert.notification.toolkit.fluxcd.io/slack-live-team-ops unchanged
provider.notification.toolkit.fluxcd.io/slack-live-team-ops unchanged
receiver.notification.toolkit.fluxcd.io/gitlab-infra-company-com unchanged
gitrepository.source.toolkit.fluxcd.io/flux-workspaces unchanged
ingressroute.traefik.containo.us/flux-receiver unchanged
The Service "webhook-receiver" is invalid: spec.clusterIP: Invalid value: "10.200.133.61": field is immutable
```

The only relevant information (according to me) is the last line, all the `unchanged` lines are noise that make the real error less visible (keep in mind that slack for example only display the first 2 lines by default).

Regards.

**Comment by invke** [comment]
I am just setting this up the notifications controller in a medium-sized cluster now and noticed this also. [Slack also truncates messages at 100,000 characters](https://api.slack.com/changelog/2018-04-truncating-really-long-messages), so if there are enough resources in the cluster, the error data (the most useful part) gets chopped off the end.

Let me know if you want me to create another issue around the truncation. Although I figured it relates quite directly with this.

Cheers.

**Comment by phillebaba** [comment]
This is a two part issue. One is that it is not possible to limit the message size in the notification controller, something that we could explore to see if it is feasible. It would mean however that the message would be cut off at some random place where it exceeds the limit.

If you want to have a "smarter" message you would need to change the event message sent by kustomize-controller so that it is not as verbose. That would probably be a better solution as you would be able to limit the message for specific events.

**Comment by invke** [comment]
@phillebaba, totally agree. I've made an [issue on the kustomize-controller](https://github.com/fluxcd/kustomize-controller/issues/190) around being able to configure the verbosity of events.

**Comment by hiddeco** [comment]
Had a chat about this with @stefanprodan a couple of weeks ago, but did not take any notes.

From what I recall, my idea at the time was to provide the "full changelog" as metadata to the notification-controller, and emit a summary of changes as a Kubernetes event and/or short notification message to other platforms.

**Comment by phillebaba** [comment]
So do you think that the truncating of the message should be done in the notification-controller instead of the event source? I guess its possible as long as the data received is in a structured format.

**Comment by hiddeco** [comment]
> So do you think that the truncating of the message should be done in the notification-controller instead of the event source?

No, I think the broadcaster should send two messages to the notification-controller.

1. The summarized / truncated message, that is also broadcasted as a Kubernetes event.
2. The enriched / full message, using a new field in our own `Event` type: https://github.com/fluxcd/pkg/blob/main/runtime/events/event.go#L33

**Comment by stefanprodan** [comment]
Error notifications coming from kustomize-controller contain now only the apply errors.
